version: '3'

services:
  rails:
    image: 'ghcr.io/rubens-create/chatwoot-main-estavel-com-kanban-e-botao-funcional:latest'
    pull_policy: always
    ports:
      - "3005:3000"
    volumes:
      - 'storage:/app/storage'
      - './docker/entrypoints/rails.sh:/app/docker/entrypoints/rails.sh'
    depends_on:
      - postgres
      - redis
    entrypoint: docker/entrypoints/rails.sh
    command:
      - bundle
      - exec
      - rails
      - s
      - '-p'
      - '3000'
      - '-b'
      - 0.0.0.0
    post_start:
      - command:
        - sh
        - '-c'
        - 'bundle exec rails db:chatwoot_prepare && bundle exec rails branding:update && if [ -n "$${BRAND_ASSETS_URL}" ]; then deployment/extract_brand_assets.sh "$${BRAND_ASSETS_URL}"; fi'
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - DEFAULT_LOCALE=pt_BR
      - FRONTEND_URL=${FRONTEND_URL}
      - INTERNAL_HOST_URL=http://rails:3000
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DB:-chatwoot_production}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - REDIS_URL=redis://redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - BAILEYS_PROVIDER_DEFAULT_CLIENT_NAME=${BAILEYS_PROVIDER_DEFAULT_CLIENT_NAME}
      - BAILEYS_PROVIDER_DEFAULT_URL=${BAILEYS_PROVIDER_DEFAULT_URL}
      - BAILEYS_PROVIDER_DEFAULT_API_KEY=${BAILEYS_PROVIDER_DEFAULT_API_KEY}
      - BAILEYS_PROVIDER_USE_INTERNAL_HOST_URL=true
      - MAILER_SENDER_EMAIL=${MAILER_SENDER_EMAIL}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - BRAND_ASSETS_URL=${BRAND_ASSETS_URL}
    restart: always
    healthcheck:
      test:
        - CMD-SHELL
        - 'wget -qO- --header="Accept: text/html" http://127.0.0.1:3000/'
      interval: 60s
      timeout: 20s
      retries: 20

  sidekiq:
    image: 'ghcr.io/SEU-USUARIO/SEU-REPO:latest'
    pull_policy: always
    volumes:
      - 'storage:/app/storage'
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - DEFAULT_LOCALE=pt_BR
      - FRONTEND_URL=${FRONTEND_URL}
      - INTERNAL_HOST_URL=http://rails:3000
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DB:-chatwoot_production}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - REDIS_URL=redis://redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - BAILEYS_PROVIDER_DEFAULT_CLIENT_NAME=${BAILEYS_PROVIDER_DEFAULT_CLIENT_NAME}
      - BAILEYS_PROVIDER_DEFAULT_URL=${BAILEYS_PROVIDER_DEFAULT_URL}
      - BAILEYS_PROVIDER_DEFAULT_API_KEY=${BAILEYS_PROVIDER_DEFAULT_API_KEY}
      - BAILEYS_PROVIDER_USE_INTERNAL_HOST_URL=true
      - MAILER_SENDER_EMAIL=${MAILER_SENDER_EMAIL}
      - RESEND_API_KEY=${RESEND_API_KEY}
    command:
      - bundle
      - exec
      - sidekiq
      - '-C'
      - config/sidekiq.yml
    restart: always
    healthcheck:
      test:
        - CMD-SHELL
        - 'ps aux | grep [s]idekiq'
      interval: 30s
      timeout: 20s
      retries: 20

  postgres:
    image: 'pgvector/pgvector:pg16'
    restart: always
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-chatwoot_production}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -h localhost -p 5432 -U $${POSTGRES_USER} -d $${POSTGRES_DB}'
      interval: 20s
      timeout: 20s
      retries: 10

  redis:
    image: 'redis:alpine'
    restart: always
    command:
      - sh
      - '-c'
      - 'redis-server --requirepass "${REDIS_PASSWORD}"'
    volumes:
      - 'redis:/data'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    healthcheck:
      test:
        - CMD-SHELL
        - 'redis-cli -h localhost -p 6379 -a $${REDIS_PASSWORD} ping'
      interval: 20s
      timeout: 20s
      retries: 10

volumes:
  storage:
  postgres:
  redis:
